{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Chart.Name }}-content
  labels:
    type: nfs
    app: {{ .Chart.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  nfs:
    server: {{ .Values.persistence.nfs.server }}
    path: {{ .Values.persistence.nfs.path }}
  mountOptions:
    - vers=3
    - rw
    - hard
    - timeo=600
    - retrans=5
{{- end }}