{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Chart.Name }}-content
  namespace: {{ .Release.Namespace }} # S'assure qu'il est dans le bon namespace
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeName: pv-{{ .Chart.Name }}-content # Force le lien avec le PV créé plus haut
{{- end }}